import { NextPage } from "next"
import { Head } from "next/document"

const About: NextPage = () => { 
    return(
        <div>
            <Head>
                <title>Progressive Web App</title>
                <meta name="description" content="Generated by Ottercode template generator" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            About page
        </div>
    )
}

export default About