import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { CardComponent } from '../shared/components'
import styles from '../shared/styles/Home.module.css'
import { ApiRouteCardData } from '../shared/constants'
import { CardDataModel } from '../shared/models'

const Home: NextPage = () => {

  const [cardInfo, setCardInfo] = useState<CardDataModel[]>()

  useEffect(() => {
    const fetchData = async () => {
      await fetch(ApiRouteCardData)
      .then(async (data) => { 
        var value = await data.json() as CardDataModel[]
        setCardInfo(value)
      })
    }
    fetchData()
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Progressive Web App</title>
        <meta name="description" content="Generated by Ottercode template generator" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps">PWA</a> template
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>src/pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          {cardInfo?.map((data: CardDataModel) => {
            return(
              <CardComponent key={data.id} title={data.title} desc={data.desc} link={data.link} />
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
export default Home
